name: 26f3861b-5297-4e7c-92fa-6d4e397ff7fe

services:
  postgres:
    image: postgres
    container_name: 26f3861b-5297-4e7c-92fa-6d4e397ff7fe-postgres
    environment:
      POSTGRES_DB: 26f3861b-5297-4e7c-92fa-6d4e397ff7fe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - 26f3861b-5297-4e7c-92fa-6d4e397ff7fe_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  26f3861b-5297-4e7c-92fa-6d4e397ff7fe_postgres_data:
